name: Check code style and run tests
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          ./test.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."
